sudo: required
language: go
go:
      - "1.12.15"
env:
  global:
    - K8S_VERSION=v1.16.4
    - secure: "FTcm2xCBxf9Ei9+NyFqj3VjrLZ/FBtW5AJDKcyXLD3Bz39GIuZSrn3jCGCjooLIGjoHAmas48eppHsPrszXv5i9KI6hOEYJTX7GKZW7i3fv2SLcMlA416GQbankiUk9frYkyS5/Jxd625SBG9yR8T/umWDGjr6cEj3Cv+FX32Org4Vl8fnfo6zMDDd6mut+EuRJyEikXTv3xEOHp7MRsC7UC2+67NMMUWv9RmlqEsqoJKt8wH6Y3kctXLuxhQNUfzNDsQ3z2dagiCIHzfm1BzAYFuCcLqFvETTvRa9i0N+K5ACvxreVg9mNBeAA9J9wfcx3WccWYC7M0XKIH7qHOgG+vAK7qW/Blsci6O0SrH1VQLZy4snIUyHx2NyfmHhSJPnKfUmK0P0VWdwRiPt9B6pa+AzkBxgRRkMLuJtPRs1ux5zVblub9l5cxYhu2jQU8SJwuEyFt6Nl7I8tR7qyfua9ZnYkm0a+7gZhSnFbmEDBlP1PIDajhj+LcA64i6j9CoJvd/ur49ewSUUseRbCHTFAzzv7/fUqrzftgKYpKix+Npr0gmRviGXj5Y4Y9wSlyXD21Cd0JuDV14R3bMdDoNeGk73FHXnP9y42mBAUyQwiLEtJlmBqO+vnOIEEkqvvorB0OUyIYnJB4qN8b+XxUU7rKYnsz2MzKRhiq5TUk6ZI="
before_install:
    - export GOPATH=$HOME/go
    - export PATH=$HOME/usr/local/go/bin:$GOPATH/bin:$PATH
    - mkdir -p $GOPATH/src/github.com/ovn-org
    - mv $TRAVIS_BUILD_DIR $GOPATH/src/github.com/ovn-org/ovn-kubernetes
    - cd $GOPATH/src/github.com/ovn-org/ovn-kubernetes

jobs:
  include:
    - stage: build
      script:
        - pushd go-controller
        -    make
        -    make windows
        -    make gofmt
        -    make install.tools
        -    make lint
        -    make check
        - popd
        - pushd dist/images
        -    if [ -n "$(git diff --stat origin/master.. | grep dist/images/Dockerfile)" ]; then make all; fi
        - popd
    - stage: e2e-kind-ovn
      before_script:
        - export GO111MODULE="on"
        - curl -fs https://chunk.io/trozet/ba750701d0af4e2b94b249ab9de27b50 -o $GOPATH/bin/kubetest
        - chmod +x $GOPATH/bin/kubetest
        - git clone --single-branch --branch $K8S_VERSION https://github.com/kubernetes/kubernetes.git $GOPATH/src/k8s.io/kubernetes/
        - pushd $GOPATH/src/k8s.io/kubernetes/
        - make WHAT="test/e2e/e2e.test vendor/github.com/onsi/ginkgo/ginkgo cmd/kubectl"
        - sudo cp ./_output/local/go/bin/kubectl /usr/local/bin/
        - popd
      script:
        - GO111MODULE="on" go get sigs.k8s.io/kind@v0.7.0
        - pushd contrib
        - ./kind.sh
        - popd
        - pushd $GOPATH/src/k8s.io/kubernetes/
        - export KUBERNETES_CONFORMANCE_TEST=y
        - export KUBECONFIG=${HOME}/admin.conf
        - travis_wait 20 kubetest --ginkgo-parallel=2 --provider=local --deployment=kind --kind-cluster-name=kind-ovn --test --test_args='--ginkgo.focus=\[sig-network\].*Conformance --disable-log-dump=false --ginkgo.skip=\[Serial\]'
        - travis_wait 20 kubetest --ginkgo-parallel=2 --provider=local --deployment=kind --kind-cluster-name=kind-ovn --test --test_args='--ginkgo.focus=\[sig-network\].*NetworkPolicy --disable-log-dump=false --ginkgo.skip=ingress\saccess|multiple\segress\spolicies|allow\segress\saccess|\[Serial\]'
      after_failure:
        - kind export logs /tmp/kind/logs
        - tar -czvf e2e-kind-ovn-${TRAVIS_COMMIT}-${TRAVIS_JOB_NUMBER}.tar.gz -C /tmp/kind/logs/ ./
        - curl -s -u ${CHUNK_USER}:${CHUNK_PASS} -T e2e-kind-ovn-${TRAVIS_COMMIT}-${TRAVIS_JOB_NUMBER}.tar.gz chunk.io | awk '{print $1"?lang=tar"}'

